### ISSUE TITLE
you are not allowed to create 'IT Asset' (itm.equipment) records

### ISSUE THREAD

**Issue by crystal-network-logistics** [trevi-software/trevi-misc#21]
An Access Error when I add an IT asset
![image](https://user-images.githubusercontent.com/89958895/162159194-5775d59f-67b4-401f-b49a-e8d147110883.png)

But I checked the access rules and found no exceptions, even I added RW privileges to user:
![image](https://user-images.githubusercontent.com/89958895/162159603-1d77eace-2182-4292-a9d6-77c890b636b8.png)

**Comment by mtelahun** [comment]
What you're looking at is Settings -> Security -> Access Rights.
The error is referring to Settings -> Security -> Record Rules

I was in a rush to port these modules from the initial author's repository to 14.0 for my own use-case so there are still some areas that need to be worked on. This is one of those areas. You can remove the rule that's causing this error and you'll be fine.

**Comment by mtelahun** [comment]
> What you're looking at is Settings -> Security -> Access Rights. The error is referring to Settings -> Security -> Record Rules
> 
> I was in a rush to port these modules from the initial author's repository to 14.0 for my own use-case so there are still some areas that need to be worked on. This is one of those areas. You can remove the rule that's causing this error and you'll be fine.

Actually, you should probably remove all the record rules created by this module:
IT Portal - Equipment
IT Portal - Access
IT Portal - Backup

**Comment by crystal-network-logistics** [comment]
Hi @mtelahun , thank you for your reply quick. It's my fault. I shouldn't have given to Portal at the same time, remove the Portal permission. e.g.:

![image](https://user-images.githubusercontent.com/89958895/162350955-883a86b4-fd9a-46f6-afa5-b2a222c6366c.png)

This will work good, thank you again~
